// Datos de ejemplo para el sistema SICS
import type { Afiliado, Medico, LugarTrabajo, ConsultaClinica, ExamenClinico, CertificadoSanitario } from "./types"

export const afiliados: Afiliado[] = [
  {
    id: "1",
    curp: "GAPA850315HBCRRL09",
    nombres: "Alberto",
    apellidoPaterno: "García",
    apellidoMaterno: "Pérez",
    fechaNacimiento: "1985-03-15",
    genero: "masculino",
    estatus: "activo",
    calle: "Av. Revolución 1234",
    colonia: "Centro",
    codigoPostal: "22000",
    ciudad: "Tijuana",
    estado: "Baja California",
    telefono: "6641234567",
    email: "alberto.garcia@email.com",
    lugarTrabajoId: "1",
    ocupacion: "Mesero",
    lugarProcedencia: "Tijuana, BC",
    fechaRegistro: "2024-01-15",
    fechaActualizacion: "2024-12-20",
  },
  {
    id: "2",
    curp: "MOLA900520MBCRRR08",
    nombres: "Laura",
    apellidoPaterno: "Morales",
    apellidoMaterno: "López",
    fechaNacimiento: "1990-05-20",
    genero: "femenino",
    estatus: "activo",
    calle: "Calle 5ta 567",
    colonia: "Zona Centro",
    codigoPostal: "22100",
    ciudad: "Tijuana",
    estado: "Baja California",
    telefono: "6649876543",
    email: "laura.morales@email.com",
    lugarTrabajoId: "2",
    ocupacion: "Cocinera",
    lugarProcedencia: "Ensenada, BC",
    fechaRegistro: "2024-02-10",
    fechaActualizacion: "2024-12-18",
  },
  {
    id: "3",
    curp: "ROHE880712HBCSRN05",
    nombres: "Enrique",
    apellidoPaterno: "Rosas",
    apellidoMaterno: "Hernández",
    fechaNacimiento: "1988-07-12",
    genero: "lgbt+",
    estatus: "pendiente",
    calle: "Blvd. Agua Caliente 890",
    colonia: "Hipódromo",
    codigoPostal: "22020",
    ciudad: "Tijuana",
    estado: "Baja California",
    telefono: "6645551234",
    email: "enrique.rosas@email.com",
    lugarTrabajoId: "3",
    ocupacion: "Bartender",
    lugarProcedencia: "Mexicali, BC",
    fechaRegistro: "2024-11-05",
    fechaActualizacion: "2024-12-28",
  },
]

export const medicos: Medico[] = [
  {
    id: "1",
    cedulaProfesional: "12345678",
    nombres: "María Elena",
    apellidoPaterno: "Sánchez",
    apellidoMaterno: "Ruiz",
    especialidad: "Medicina General",
    telefono: "6641112233",
    email: "dra.sanchez@salud.gob.mx",
    estatus: "activo",
    firmaDigitalUrl: "/firmas/firma-sanchez.png",
    fechaRegistro: "2023-01-10",
  },
  {
    id: "2",
    cedulaProfesional: "87654321",
    nombres: "Roberto",
    apellidoPaterno: "Mendoza",
    apellidoMaterno: "Torres",
    especialidad: "Epidemiología",
    telefono: "6644445566",
    email: "dr.mendoza@salud.gob.mx",
    estatus: "activo",
    firmaDigitalUrl: "/firmas/firma-mendoza.png",
    fechaRegistro: "2022-06-15",
  },
]

export const lugaresTrabajo: LugarTrabajo[] = [
  {
    id: "1",
    codigo: "A-01",
    nombre: "Restaurante El Buen Sabor",
    zonaTrabajo: "Zona Centro",
    calle: "Av. Revolución 500",
    colonia: "Centro",
    codigoPostal: "22000",
    telefono: "6641234000",
    ciudad: "Tijuana",
    estado: "Baja California",
    estatus: "activo",
  },
  {
    id: "2",
    codigo: "A-02",
    nombre: "Hotel Plaza Marina",
    zonaTrabajo: "Zona Río",
    calle: "Blvd. Sánchez Taboada 1500",
    colonia: "Zona Río",
    codigoPostal: "22010",
    telefono: "6645550000",
    ciudad: "Tijuana",
    estado: "Baja California",
    estatus: "activo",
  },
  {
    id: "3",
    codigo: "B-01",
    nombre: "Bar La Cantina",
    zonaTrabajo: "Zona Centro",
    calle: "Calle 6ta 234",
    colonia: "Centro",
    codigoPostal: "22000",
    telefono: "6649998877",
    ciudad: "Tijuana",
    estado: "Baja California",
    estatus: "activo",
  },
]

export const consultasClinicas: ConsultaClinica[] = [
  {
    id: "1",
    afiliadoId: "1",
    medicoId: "1",
    fecha: "2024-12-15",
    tensionArterial: "120/80",
    diagnostico: "Paciente sano, apto para trabajo",
    tratamiento: "Ninguno requerido",
    comentarios: "Se recomienda exámenes de rutina",
    examenes: [],
  },
  {
    id: "2",
    afiliadoId: "2",
    medicoId: "2",
    fecha: "2024-12-10",
    tensionArterial: "118/75",
    diagnostico: "Paciente sana, sin hallazgos patológicos",
    tratamiento: "Continuar con chequeos regulares",
    comentarios: "Próxima cita en 6 meses",
    examenes: [],
  },
]

export const examenesClinicosData: ExamenClinico[] = [
  {
    id: "1",
    afiliadoId: "1",
    consultaId: "1",
    tipoExamen: "VDRL",
    fechaOrden: "2024-12-15",
    fechaResultado: "2024-12-17",
    fechaProximoExamen: "2025-03-17",
    resultadoVDRL: "negativo",
    resultado: "No reactivo",
    laboratorioId: "1",
  },
  {
    id: "2",
    afiliadoId: "1",
    consultaId: "1",
    tipoExamen: "VIH",
    fechaOrden: "2024-12-15",
    fechaResultado: "2024-12-17",
    fechaProximoExamen: "2025-06-17",
    resultado: "No reactivo",
    laboratorioId: "1",
  },
  {
    id: "3",
    afiliadoId: "2",
    consultaId: "2",
    tipoExamen: "Papanicolaou",
    fechaOrden: "2024-12-10",
    fechaResultado: "2024-12-14",
    fechaProximoExamen: "2025-12-14",
    resultado: "Normal",
    laboratorioId: "1",
  },
]

export const certificados: CertificadoSanitario[] = [
  {
    id: "1",
    folio: "SICS-2024-00001",
    afiliadoId: "1",
    medicoId: "1",
    fechaEmision: "2024-12-17",
    fechaVigencia: "2025-01-17",
    estatus: "vigente",
    qrCode: "https://sics.gob.mx/verificar/SICS-2024-00001",
  },
]

// Catálogos
export const tiposExamen = [
  {
    id: "1",
    codigo: "VDRL",
    nombre: "VDRL (Sífilis)",
    descripcion: "Prueba serológica para sífilis",
    frecuenciaRenovacionDias: 90,
    obligatorio: true,
  },
  {
    id: "2",
    codigo: "VIH",
    nombre: "VIH/SIDA",
    descripcion: "Prueba de detección de VIH",
    frecuenciaRenovacionDias: 180,
    obligatorio: true,
  },
  {
    id: "3",
    codigo: "PAP",
    nombre: "Papanicolaou",
    descripcion: "Citología cervical",
    frecuenciaRenovacionDias: 365,
    obligatorio: false,
  },
  {
    id: "4",
    codigo: "HEP",
    nombre: "Hepatitis B y C",
    descripcion: "Marcadores de hepatitis",
    frecuenciaRenovacionDias: 180,
    obligatorio: true,
  },
  {
    id: "5",
    codigo: "BH",
    nombre: "Biometría Hemática",
    descripcion: "Conteo sanguíneo completo",
    frecuenciaRenovacionDias: 180,
    obligatorio: false,
  },
]

export const laboratorios = [
  {
    id: "1",
    nombre: "Laboratorio Central de Salud Pública",
    direccion: "Av. Constitución 1000",
    telefono: "6641000000",
    email: "lab.central@salud.gob.mx",
    estatus: "activo" as const,
    examenesAutorizados: ["VDRL", "VIH", "PAP", "HEP", "BH"],
  },
  {
    id: "2",
    nombre: "Laboratorio Clínico ABC",
    direccion: "Blvd. Díaz Ordaz 500",
    telefono: "6642000000",
    email: "contacto@lababc.com",
    estatus: "activo" as const,
    examenesAutorizados: ["VDRL", "VIH", "BH"],
  },
]
